### ISSUE TITLE
powerful

### ISSUE THREAD

**Issue by invlpg** [donnaskiez/nmi-callback-handler#1]
![ezgif com-gif-maker_1](https://user-images.githubusercontent.com/75157064/235367127-0476204b-0a3b-4c67-8771-f0053e577665.gif)
![giphy (9)](https://user-images.githubusercontent.com/75157064/235367169-a6888c4d-0f4c-4641-bec5-1a87abcdab6c.gif)

**Comment by donnaskiez** [comment]
![Tj9Lc1G (1)](https://user-images.githubusercontent.com/54422048/235420931-383eacd5-f0e1-4e22-99b2-ad0c71ce9a22.gif)

**Comment by invlpg** [comment]
https://github.com/donnaskiez/nmi-callback-handler/blob/master/nmi-callback-handler/driver.c#L255-L260

maybe check if ptr is inside an executable section that isnt discardable

**Comment by invlpg** [comment]
![image](https://user-images.githubusercontent.com/75157064/236064166-b9f26923-924d-4dc9-b908-d06b84d57e32.png)
